language: java
sudo: false
install:
  - pip install --user sphinx
script:
  - make html
after_success:
  - PATH="$HOME/.local/bin:$PATH" ./push-gh-pages.sh
env:
  global:
    - GIT_USER_NAME=travis
    - GIT_USER_EMAIL=travis@embulk.org
    - secure: K5qT2PcCP/40dNW+1H4NZ6y1+GAZbyP/lMQ1tSMsAICGkMQ/A+Mp5wtnIGIsAf6JGcJ1PvpCoLE1V6wKFL5fEwxi4SRcTnZTh9PkeAk8dgezOMoX4EqeZiQAYv4MM2zKL+Gr6QivjmRA7I5jrZCo8JyaA5XfQ7ygjICKNJy8NaE=
