#!/bin/bash

set -xe

# skip pull requests
[ "$TRAVIS_PULL_REQUEST" != "false" ] && exit 0

# build only on master branch
[ "$TRAVIS_BRANCH" != "master" -a "$TRAVIS_BRANCH" != "$(git describe --tags --always HEAD)" ] && exit 0

revision="$(git rev-parse HEAD)"
remote="https://github.com/embulk/embulk.github.io.git"

# unshallow to make new commits
git fetch --unshallow || echo "using complete repository."

# create a clean clone
rm -rf gh_pages
git clone . gh_pages
cd gh_pages

# add the remote repo as travis_push
git remote add travis_push "$remote"
git fetch travis_push

# checkout master branch of the remote repo as gh-pages branch
git checkout -b gh-pages travis_push/master

# update docs directory of this branch
rm -rf docs
cp -a ../build/html docs
git add --all docs

# make a new commit
git config user.name "$GIT_USER_NAME"
git config user.email "$GIT_USER_EMAIL"
git commit -m "Updated document $revision" || true

# do nothing if there're no changes
git show | grep -E '^[+-] ' | grep -Eqv 'Generated by|Generated on|Search.setIndex|meta name="date" content='
if [ $? -ne 0 ];then
    echo "No document changes."
    exit 0
fi

# push the changes
set +x
git config credential.helper "store --file=$HOME/.git_credentials"
echo "https://$GITHUB_TOKEN:@github.com" > "$HOME/.git_credentials"
trap "rm -rf $HOME/.git_credentials" EXIT
set -x
git push travis_push gh-pages:master
